### ISSUE TITLE
Repository metadata URL is invalid

### ISSUE THREAD

**Issue by sschuberth** [dart-lang/core#138]
This

https://github.com/dart-lang/core/blob/58762460f95fd6ed4b9f30138be22863b742aef4/pkgs/args/pubspec.yaml#L6

should have "tree" before the "main" branch name to make it an existing URL so it reads

https://github.com/dart-lang/core/tree/main/pkgs/args

**Comment by devoncarew** [comment]
Agreed! PRs welcome :)

**Comment by sschuberth** [comment]
> Agreed! PRs welcome :)

[Here](https://github.com/dart-lang/core/pull/140) you go.
