### ISSUE TITLE
pathContext.fromUri() mishandles encoded colons after drive letters

### ISSUE THREAD

**Issue by DanTup** [dart-lang/core#545]
This came up via https://github.com/dart-lang/sdk/issues/53000. I had swapped some code from doing `uri.toFilePath()` to `pathContext.fromUri(uri)` to support testing Windows-style paths on MacOS.

However it turns out there is a difference in behaviour when the colon after a drive letter is percent-encoded:

```dart
  final fileUris = [
    'file:///C%3A/Dev/Test%20Projects/dart_application_3',
    'file:///C:/Dev/Test%20Projects/dart_application_3'
  ];
  for (final fileUri in fileUris) {
    final path1 = Uri.parse(fileUri).toFilePath();
    final path2 = pathContext.fromUri(fileUri);
    print('Uri.parse($fileUri).toFilePath():\n    $path1');
    print('pathContext.fromUri($fileUri):\n    $path2');
  }
```

```
Uri.parse(file:///C%3A/Dev/Test%20Projects/dart_application_3).toFilePath():
    C:\Dev\Test Projects\dart_application_3

pathContext.fromUri(file:///C%3A/Dev/Test%20Projects/dart_application_3):
    \C:\Dev\Test Projects\dart_application_3

Uri.parse(file:///C:/Dev/Test%20Projects/dart_application_3).toFilePath():
    C:\Dev\Test Projects\dart_application_3

pathContext.fromUri(file:///C:/Dev/Test%20Projects/dart_application_3):
    C:\Dev\Test Projects\dart_application_3
```

Since `toFilePath()` handles this (and VS Code has been producing URIs in this format forever), I believe the encoding of the colon is valid (although I've failed to find anything that seems explicit in the spec) and should be handled.

**Comment by lrhn** [comment]
Be aware that the fix for this issue is not recognized by canonicalization. Even if `file:///c:/foo` and `file:///c%3a/foo` represent the same file, they do not canonicalize to the same string. (Which isn't unique, canonicalization doesn't handle escapes at all, `file:///a` and `file:///%61` also do not canonicalize to the same path, even if they are the same URI.)

**Comment by lrhn** [comment]
Just a comment. I was working with the code and started wondering about canonicalization. So I decided to put a notice of this at the point where the `%3a` support was added, in case someone wants to figure out if it's international or not.

It's at least consistent.
