### ISSUE TITLE
New `replaceWhere` method on `List`

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/core#652]
I would like to propose a new method for `List` called `replaceWhere` or a similar name.

I have some use cases where I have a full list of objects from a class. But something else in my program updates and I would need to (as of right now) save the list, iterate through it and replace it where it matches a test function, for a new value of that same type.

It could probably be something like this:

```dart
Iterable<T> replaceWhere(bool Function(T) test, T Function(T) replace) sync* {
  for (final item in this) {
    if (test(item)) {
      yield replace(item);
    } else {
      yield item;
    }
  }
}

Iterable<T> replaceWhereNot(bool Function(T) test, T Function(T) replace) sync* {
  for (final item in this) {
    if (test(item)) {
      yield item;
    } else {
      yield replace(item);
    }
  }
}
```

**Comment by feinstein** [comment]
I confess I didn't realise this could be done with a map, the traditional way to replace is to find the index, then replace in the index, probably my mind is too tied to my old C days lol.

I would argue that a `replaceWhere` could be useful for people that didn't realise it can be done simply with a map, and are going the "traditional" route. Given that we have `replaceRange`, this can also point people out to the path of "you need an index".

**Comment by lrhn** [comment]
Reading this again, the name `replaceWhere` is misleading, what's asked for is more like `mapIf`.

A `replace*` sounds like its mutating, as the later comment also reads it.

That's something you _could_ do on a list, as
```dart
extension ListUpdate<T> on List<T> {
  void updateAll(T Function(T) convert) {
    for (var i = 0; i < length; i++) this[i] = convert(this[i]);
  }
  void updateWhere(bool Function(T) test, T Function(T) convert) {
     for (var i = 0; i < length; i++) {
       var value = this[i];
       if (test(value)) this[i] = convert(value);
     }
  }
  void updateNotNull(T? Function(T) convert) {
     for (var i = 0; i < length; i++) {
       if (convert(this[i]) case var value?) this[i] = value;
     }
}
```   

But it's also just four simple lines to write diretly, and then you can inline the test and update operations, instead of having to create (and call) them as functions.
```dart
for (var i = 0; i < list.length; i++) {
  var value = list[i];
  if (test(value)) list[i] = update(value);
}
```

**Comment by feinstein** [comment]
I agree, but it's also nice to have simple APIs that keep things simple to read, follow, and avoids boilerplate code that's very repeatable.
